import random
numero1 = random.randint(0, 9)
numero2 = random.randint(0, 9)
numero3 = random.randint(0, 9)
print(f"Ensimmäinen koodi on {numero1}{numero2}{numero3}")
numero4 = random.randint(1, 6)
numero5 = random.randint(1, 6)
numero6 = random.randint(1, 6)
numero7 = random.randint(1, 6)
print(f"Toinen koodi on {numero4}{numero5}{numero6}{numero7}")